import { Toaster } from "react-hot-toast";
import "./globals.css";
import Navigation from "@/components/navigation/navigation";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="antialiased">
        <Navigation />
        <Toaster
          position="top-center"
          toastOptions={{
            className: "bg-shade text-primary",
            duration: 3000,
          }}
        />
        {children}
      </body>
    </html>
  );
}
